name: "deploy cdflow2 release"
description: "deploy cdflow2 release"

inputs:
  release_name:
    description: "Name of release, default should be adequate"
    required: true
    default: "main-${{ github.run_number }}-${{ github.sha }}"
  capability:
    description: "key to find AWS authentication info in github actions secrets context. E.g. 'CAPINTERFACE', 'CAPAUTOMATION', etc."
    required: true
  environment:
    description: "live or aslive"
    required: true

runs:
  using: "composite"
  steps:
    if: ${{ github.ref == 'refs/heads/main' }}
  - name: Check out code
    uses: actions/checkout@v2

  - name: Notify Teams
    uses: toko-bifrost/ms-teams-deploy-card@3.1.2
    with:
      github-token: ${{ github.token }}
      webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}
      card-layout-exit: compact
      show-on-start: false

  - name: Get latest cdflow2
    run: curl -Lo infra/cdflow2 https://github.com/mergermarket/cdflow2/releases/latest/download/cdflow2-linux-amd64 && chmod +x infra/cdflow2

  - name: Deploy to ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ format('secrets,{0}_AWS_ACCESS_KEY_ID', ${{ inputs.capability }}
      AWS_SECRET_ACCESS_KEY: ${{ format('secrets,{0}_AWS_SECRET_ACCESS_KEY', ${{ inputs.capability }}
    run: infra/cdflow2 deploy aslive ${{ inputs.release_name }}
