name: "Java Build"
description: "Build Java application in Github"

runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Initialize CodeQL
    uses: github/codeql-action/init@v1
    with:
      languages: java

  - name: Set up JDK11
    uses: actions/setup-java@v2
    with:
      distribution: 'temurin'
      java-version: '11'
      cache: 'maven'
      server-id: github
      settings-path: ${{ github.workspace }}

  - name: Cache Maven packages
    uses: actions/cache@v2
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      restore-keys: ${{ runner.os }}-m2-

# assumes repository is defined in pom.xml. mvn deploy runs all prerequisite steps including build
  - name: Deploy Snapshot
    run: mvn -B -V -U deploy -s $GITHUB_WORKSPACE/settings.xml
    env:
      GITHUB_TOKEN: ${{ secrets.IONA_GITHUB_PACKAGE_TOKEN }}

